### ISSUE TITLE
Разработка архитектуры проекта и распределение ролей

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-1-chat#2]
Требуется разработать архитектуру чата:
* выбрать подходы и технологии, которые будут использоваться при разработке (паттерны проектирования, сторонние библиотеки — тут фиксировано, JQuery только для AJAX);
* определить, из каких крупных компонентов будет состоять решение;
* распределить обязанности участников между различными компонентами и различными видами деятельности, создав на каждую подзадачу «issue» и назначив её на участника.

**Comment by dynamic-pie** [comment]
Здравствуйте, в связи с тем, что буду отчисляться, можно ли меня исключить
из проекта и назначить за старшего Андрея Солнышкова?

2017-08-08 0:05 GMT+03:00 NowUooMe <notifications@github.com>:

**Comment by Mazdaywik** [comment]
Вот, теперь я увидел, как можно делать комментарии в GitHub, отвечая на письма.
