### ISSUE TITLE
Сообщать пользователю, если пароли при регистрации не совпадают

### ISSUE THREAD

**Issue by adrian-raskl** [bmstu-iu9/utp2017-1-chat#24]
(мне просто нравится создавать эти штуки)

**Comment by Mazdaywik** [comment]
И это правильно.

Теперь, если коммиту, решающему эту задачу, приписать в сообщении #24, то он привяжется к этому issue. А если приписать «close #24» или «fix #24», то эта «штука» закроется при попадании коммита в ветку master.
