### ISSUE TITLE
Исправление бага с "Выйти" в комнате

### ISSUE THREAD

**Issue by morozyto** [bmstu-iu9/utp2017-1-chat#45]
При нажатии этой кнопки вылетает необработанная ошибка.

**Comment by adrian-raskl** [comment]
![2017-08-15 03-36-54](https://user-images.githubusercontent.com/16825435/29297670-32feaf58-816b-11e7-87d7-31b7107726dd.png)

**Comment by adrian-raskl** [comment]
Виновник бага ![mozilla-firefox](https://user-images.githubusercontent.com/16825435/29321724-0e8b5d3c-81e4-11e7-908f-d7738774e795.jpg)
