### ISSUE TITLE
Буквы "Ч А Т" (фронтэнд)

### ISSUE THREAD

**Issue by morozyto** [bmstu-iu9/utp2017-1-chat#51]
![default](https://user-images.githubusercontent.com/23277466/29369477-613ac8ac-82ab-11e7-81af-941857c5c9db.png)
Буквы "Ч А Т" разве не должны быть на переднем фоне?

**Comment by adrian-raskl** [comment]
Это из-за кривой кнопки загрузки картинок, мы же ждем нормальный фронтенд, а это временное. Задачу закрываю.
