### ISSUE TITLE
Доделать онлайн-пользователей

### ISSUE THREAD

**Issue by morozyto** [bmstu-iu9/utp2017-1-chat#76]
В данный момент пользователь появляется онлайн только в момент отправки первого сообщения.

**Comment by Ra7777** [comment]
Пользователь, который заходит в комнату, видит пользователей, которые там уже находятся.

**Comment by morozyto** [comment]
@Ra7777 попробуй пообновлять страницу у одного из пользователей. У меня не совсем адекватно показывался онлайн.

Хочу сделать, чтобы клиент запрашивал раз в 15 секунд информацию о пользователях онлайн и загружал их разом. Онлайн пользователь - тот, кто делал подобный запрос в течение 30 последних секунд. Через длинные запросы реализовать это мне кажется невозможным, или по-крайней мере очень сложным, если хотеть, чтобы при подключении к чату, пользователь сразу появлялся онлайн.
